GET http://127.0.0.1:8000/api/producto?page=1&limit=15&q=
Accept: application/json
Authorization: Bearer 43|FazrNX6nkmHpdumikjaX1pCdq6fxncGTW7V2inBO

### Guardar Productos

POST http://127.0.0.1:8000/api/producto
Accept: application/json
Content-Type: application/json

{
    "nombre": "ESCRITORIO GAMER",
    "precio": 949.97,
    "stock": 6,
    "descripcion": "de madera",
    "categoria_id": 1
}

### eliminar
DELETE http://127.0.0.1:8000/api/producto/5
Accept: application/json
Authorization: Bearer 43|FazrNX6nkmHpdumikjaX1pCdq6fxncGTW7V2inBO